### ISSUE TITLE
Informal german version

### ISSUE THREAD

**Issue by schongo** [bookwhen/i18n#2]
In german language there is that concept of formal/informal speech. Would you be able to integrate an informal version as an option of choice if I created one?

**Comment by jopotts** [comment]
Hi @schongo. Thanks for the translations. The system is using the 'de' locale code for the current German translation you've provided, so it can only have the one set for that code. So I think to keep things simple you should use the form (formal/informal) that you think would be most appropriate for most users of the system. ie. Probably just stick with what you've already provided.

The system is also using the official Rails translations for some of the built in text too:
https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

Note that there are 3 optional sub-regions for German there: de-DE, de-CH (Switzerland), and de-AT (Austria). So we have additional scope to split the translation you've provided into 3 later on, but let's keep it simple for now.
